# VHDLinter Config

directory: "./testing_vhdl/"

CODE_CHECK: True
FORMATING: False
BACKUP: True

# Code check settings
file_name_check: True
print2console: True
print2file: False
file_out_name: "VHDLinter_out.txt"
file_out_dir: "./testing_linter_out/"

# Formating settings
rm_bad_whitespaces: False
tab2space: True
pretty_comments: True
spaces_per_tab: 4

# Backup settings
bak_directory: "./.bak/"

# More settings
max_line_length: 80
max_signal_name_length: 24
max_var_name_length: 24

colors:
    # "yellow", "cyan", "magenta", "blue", "green", "white"
    filename: "yellow"
    warning: "red"

# "123": Linter output is ordered by lines
# "132": Linter output is ordered by error types #TODO
linter_out_order: "123"
